spring:
  application:
    name: order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.129:3306/SpringCloud_Sell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
