spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.131:3306/SpringCloud_Sell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    show-sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  redis:
    host: 192.168.199.131
    port: 6379
    password: 123456
env:
  dev
